### ISSUE TITLE
Build fail due to  https://art-bobcat.autodesk.com not found

### ISSUE THREAD

**Issue by rick-yhchen1013** [Autodesk/AutodeskMachineControlFramework#32]
user@user-VBox:/work/harbortek/AutodeskMachineControlFramework$ ./build_clean_linux64.sh 

Directory /work/harbortek/AutodeskMachineControlFramework/build already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/Output already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/DevPackage already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/DevPackage/Plugins already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/DevPackage/Framework already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/DevPackage/Framework/HeadersDev already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/DevPackage/Framework/HeadersDev/CppDynamic already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/DevPackage/Framework/HeadersDriver already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/DevPackage/Framework/HeadersDriver/CppDynamic already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/DevPackage/Framework/InterfacesDev already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/DevPackage/Framework/PluginCpp already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/DevPackage/Framework/PluginPython already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/DevPackage/Framework/Dist already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/Framework already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/Framework/HeadersDev already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/Framework/HeadersDev/CppDynamic already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/Framework/HeadersDriver already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/Framework/HeadersDriver/CppDynamic already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/Framework/InterfacesDev already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/Framework/PluginCpp already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/Client already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/Client/public already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/Client/src already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/Client/src/plugins already exists

Directory /work/harbortek/AutodeskMachineControlFramework/build/Client/dist already exists

git hash: 1aa976a

Building Resource builder (Win64)...

Building Resource builder (Linux64)...

Building Resource builder (LinuxARM)...

Building Go Server...

npm ERR! code ENOTFOUND

npm ERR! syscall getaddrinfo

npm ERR! errno ENOTFOUND

npm ERR! network request to https://art-bobcat.autodesk.com:443/artifactory/api/npm/autodesk-npm-virtual/vuetify/-/vuetify-2.3.15.tgz failed, reason: getaddrinfo ENOTFOUND art-bobcat.autodesk.com

npm ERR! network This is a problem related to network connectivity.

npm ERR! network In most cases you are behind a proxy or have bad network settings.

npm ERR! network 

npm ERR! network If you are behind a proxy, please make sure that the

npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:

npm ERR!     /home/user/.npm/_logs/2021-08-30T06_33_27_314Z-debug.log

**Comment by DocVaughan** [comment]
I'm seeing this same error. @rick-yhchen1013, were you able to figure it out?

**Comment by alexanderoster** [comment]
Apologies for the late reply. This has been fixed quite some time ago.
