### ISSUE TITLE
Failing to login

### ISSUE THREAD

**Issue by 1161744** [Autodesk/AutodeskMachineControlFramework#48]
I just installed Autodesk Machine Control Framework. However, when I open the server in http://127.0.0.1:8869/  it keeps asking me for a login. I dont have the credentials nor can I find where to create them.

![autodesk](https://user-images.githubusercontent.com/73605330/215720338-c2a34422-fe14-4a15-b116-4ade87bfa9d5.png)

**Comment by alexanderoster** [comment]
Hi there, 

the sample application comes just with "test"/"test" credentials.
